# Generated by Django 4.2.8 on 2026-05-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('username', models.CharField(max_length=55, unique=True)),
                ('email', models.EmailField(blank=True, max_length=55)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
