# Generated by Django 4.2.8 on 2026-05-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('delete', 'Delete'), ('updated', 'Update')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
