# Generated by Django 4.2.8 on 2026-05-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auditlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='crud.admins'),
        ),
    ]
