# Generated by Django 4.2.8 on 2026-05-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auditlogs_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
