# Generated by Django 4.2.8 on 2026-05-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_admins_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('change_type', models.CharField(choices=[('email', 'Email Change'), ('password', 'Password Change')], max_length=20)),
                ('new_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.admins')),
            ],
        ),
    ]
