# Generated by Django 4.2.8 on 2026-05-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_pendingverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
